server:
  port: 8081
  servlet:
    context-path: /api
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/todomaneiroDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
